<?php

// A module to display the maps visualization.

/**
 * Implements hook_menu().
 */
function clio_analyze_maps_menu() {
  $items = array();
  $type = variable_get('clio_analyze_default', '') == 'maps' ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK;
  $items['analyze/maps'] = array(
    'title'            => 'Maps',
    'page callback'    => "clio_analyze_maps_view",
    'access arguments' => array('analyze datasets'),
    'type'             => $type,
    'weight'           => 1,
  );
  return $items;
}


/**
 * Add API url to configuration form.
 */
// TODO Add parameters.
function clio_analyze_maps_form_clio_analyze_config_form_alter(&$form, &$form_state, $form_id) {
  $config = variable_get('clio_analyze_maps', array());
  $form['clio_analyze_maps'] = array(
    '#type' => 'fieldset',
    '#title' => t('Maps'),
    '#tree' => TRUE,
    '#collapsible' => TRUE, 
    '#collapsed' => FALSE,
  );
  $form['clio_analyze_maps']['api'] = array(
    '#type'  => 'textfield',
    '#title' => t('API'),
    '#description' => t('The url of the API providing the maps.'),
    '#default_value' => isset($config['api']) ? $config['api'] : '',
    // TODO Validate function does not work for tree children:
    // Notice: Undefined index: clio_analyze_maps[api] in clio_validate_api() 
    // '#element_validate' => array('clio_validate_api'),
  );
  $form['clio_analyze_maps']['height'] = array(
    '#type'  => 'textfield',
    '#title' => t('Height'),
    '#size' => 4,
    '#maxlength' => 4,
    '#field_suffix' => 'px',
    '#description' => t('The height of the iframe.'),
    '#default_value' => isset($config['height']) ? $config['height'] : '500',
  );
  $form['#submit'][] = 'clio_analyze_maps_config_submit';
}


function clio_analyze_maps_config_submit(&$form, &$form_state) {
  $settings = $form_state['values']['clio_analyze_maps'];
  foreach ($settings as $key => $value) {
    if (!$value['api']) {
      unset($settings[$key]);
    }
  }
  variable_set('clio_analyze_maps', $settings);
}


/*
 * Display the visualization.
 */
function clio_analyze_maps_view() {
  $query = array(
    'action' => 'map',
    // 'year' => max($startyear, $yearmin),
    // 'lasty' => $endyear,
  );
  return clio_analyze_view('maps', $query);
}

