<?php

// A module to display the charts visualization.

/**
 * Implements hook_menu().
 */
function clio_analyze_charts_menu() {
  $items = array();
  $type = variable_get('clio_analyze_default', '') == 'charts' ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK;
  $items['analyze/charts'] = array(
    'title'            => 'Charts',
    'page callback'    => "clio_analyze_charts_view",
    'access arguments' => array('analyze datasets'),
    'type'             => $type,
    'weight'           => 4,
  );
  return $items;
}


/**
 * Add API url to configuration form.
 */
// TODO Add parameters.
function clio_analyze_charts_form_clio_analyze_config_form_alter(&$form, &$form_state, $form_id) {
  $config = variable_get('clio_analyze_charts', array());
  $form['clio_analyze_charts'] = array(
    '#type' => 'fieldset',
    '#title' => t('Charts'),
    '#tree' => TRUE,
    '#collapsible' => TRUE, 
    '#collapsed' => FALSE,
  );
  $form['clio_analyze_charts']['api'] = array(
    '#type'  => 'textfield',
    '#title' => t('API'),
    '#description' => t('The url of the API providing the charts.'),
    '#default_value' => isset($config['api']) ? $config['api'] : '',
  );
  $form['clio_analyze_charts']['height'] = array(
    '#type'  => 'textfield',
    '#title' => t('Height'),
    '#size' => 4,
    '#maxlength' => 4,
    '#field_suffix' => 'px',
    '#description' => t('The height of the iframe.'),
    '#default_value' => isset($config['height']) ? $config['height'] : '500',
  );
  $form['#submit'][] = 'clio_analyze_charts_config_submit';
}


function clio_analyze_charts_config_submit(&$form, &$form_state) {
  $settings = $form_state['values']['clio_analyze_charts'];
  foreach ($settings as $key => $value) {
    if (!$value['api']) {
      unset($settings[$key]);
    }
  }
  variable_set('clio_analyze_charts', $settings);
}


/*
 * Display the visualization.
 */
function clio_analyze_charts_view() {
  return clio_analyze_view('charts');
}

