<?php

// A module to display the graph visualization.

/**
 * Implements hook_menu().
 */
function clio_analyze_graphs_menu() {
  $items = array();
  $type = variable_get('clio_analyze_default', '') == 'graphs' ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK;
  $items['analyze/graphs'] = array(
    'title'            => 'Graphs',
    'page callback'    => 'clio_analyze_graphs_view',
    'access arguments' => array('analyze datasets'),
    'type'             => $type,
    'weight'           => 2,
  );  
  return $items;
}


/**
 * Add API url to configuration form.
 */
// TODO Add parameters.
function clio_analyze_graphs_form_clio_analyze_config_form_alter(&$form, &$form_state, $form_id) {
  $config = variable_get('clio_analyze_graphs', array());
  $form['clio_analyze_graphs'] = array(
    '#type' => 'fieldset',
    '#title' => t('Graphs'),
    '#tree' => TRUE,
    '#collapsible' => TRUE, 
    '#collapsed' => FALSE,
  );
  $form['clio_analyze_graphs']['api'] = array(
    '#type'  => 'textfield',
    '#title' => t('API'),
    '#description' => t('The url of the API providing the graphs.'),
    '#default_value' => isset($config['api']) ? $config['api'] : '',
  );
  $form['clio_analyze_graphs']['height'] = array(
    '#type'  => 'textfield',
    '#title' => t('Height'),
    '#size' => 4,
    '#maxlength' => 4,
    '#field_suffix' => 'px',
    '#description' => t('The height of the iframe.'),
    '#default_value' => isset($config['height']) ? $config['height'] : '500',
  );
  $form['#submit'][] = 'clio_analyze_graphs_config_submit';
}


function clio_analyze_graphs_config_submit(&$form, &$form_state) {
  $settings = $form_state['values']['clio_analyze_graphs'];
  foreach ($settings as $key => $value) {
    if (!$value['api']) {
      unset($settings[$key]);
    }
  }
  variable_set('clio_analyze_graphs', $settings);
}


/*
 * Display the visualization.
 */
function clio_analyze_graphs_view() {
  $query = array(
    'aggr' => 'on',
  );
  return clio_analyze_view('graphs', $query);
}

