<?php

/**
 * Implements hook_menu().
 */
function clio_search_menu() {
  $items = array();
  $items['datasets'] = array(
    'title' => 'Datasets',
    'page callback' => 'clio_search_intro',
    'access arguments' => array('search datasets'),
    'expanded' => TRUE,
  );
  $items['datasets/search'] = array(
    'title' => 'Select',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('clio_search_select_form'),
    'access arguments' => array('search datasets'),
    'type'             => MENU_CALLBACK,
    'weight' => 13,
  );
  $items['datasets/search/modern'] = array(
    'title' => 'Modern',
    'access arguments' => array('search datasets'),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['datasets/search/historical'] = array(
    'title' => 'Historical',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('clio_search_select_form', 'historical'),
    'access arguments' => array('search datasets'),
    'type'             => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  $items['datasets/searchresults'] = array(
    'title' => 'Search results',
    'page callback'    => 'clio_search_results',
    'access arguments' => array('search datasets'),
    'type'             => MENU_CALLBACK,
  );
  $items['datasets/download'] = array(
    'page callback'    => 'clio_search_download',
    'page arguments'   => array(2),
    'access arguments' => array('download datasets'),
    'type'             => MENU_CALLBACK,
  );
  $items['admin/config/clio/search'] = array(
    'title' => 'Search',
    'description' => t('Configure Clio Infra search services'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clio_search_config_form'),
    'access arguments' => array('administer clioinfra'),
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function clio_search_permission() {
  return array(
    'search datasets' => array(
      'title' => t('Search and filter datasets'),
    ),
    'download datasets' => array(
      'title' => t('Download search results as zip file'),
    ),
  );
}


function clio_search_intro() {
  drupal_goto('datasets/search');
}


function clio_search_libraries_info() {
  $libraries['multiselect.js'] = array(
    'name' => 'multiselect.js',
    'vendor url' => 'http://loudev.com',
    'download url' => 'http://loudev.com',
    'version arguments' => array(
      'file' => 'bower.json',
       // 0.x: "version": "0.9.10"
      'pattern' => '@version": "([0-9\.]+)@',
    ),
    'files' => array(
      'js' => array(
        'js/jquery.multi-select.js',
      ),
      'css' => array(
        'css/multi-select.css',
      ),
    ),
  );
  $libraries['quicksearch'] = array(
    'name' => 'quicksearch',
    'vendor url' => 'https://github.com/riklomas/quicksearch',
    'download url' => 'https://github.com/riklomas/quicksearch',
    'version' => '0.0',
    'files' => array(
      'js' => array(
        'jquery.quicksearch.js',
      ),
    ),
  );
  $libraries['jquery.typeahead'] = array(
    'name' => 'jquery.typeahead',
    'vendor url' => 'http://www.runningcoder.org/jquerytypeahead',
    'download url' => 'http://www.runningcoder.org/jquerytypeahead',
    'version arguments' => array(
      'file' => 'bower.json',
      'pattern' => '@version": "([0-9\.]+)@',
    ),
    'files' => array(
      'js' => array(
        'dist/jquery.typeahead.min.js',
      ),
      'css' => array(
        'dist/jquery.typeahead.min.css',
      ),
    ),
  );
  return $libraries;
}


// TODO Add parameters.
function clio_search_config_form($form, &$form_state) {
  $form = array();
  $form['clio_search_search_url'] = array(
    '#type'  => 'textfield',
    '#title' => t('Search API'),
    '#description' => t('The url of the API providing the search results. E.g. http://api.example.com/search'),
    '#default_value' => variable_get('clio_search_search_url', ''),
    '#element_validate' => array('clio_validate_api'),
  );
  $form['clio_search_download_url'] = array(
    '#type'  => 'textfield',
    '#title' => t('Download API'),
    '#description' => t('The url of the API providing the download files.'),
    '#default_value' => variable_get('clio_search_download_url', ''),
    '#element_validate' => array('clio_validate_api'),
  );
  $form['clio_search_geocode_url'] = array(
    '#type'  => 'textfield',
    '#title' => t('Geocode API'),
    '#description' => t('The url of the API providing the geocodes and names of historical countries.'),
    '#default_value' => variable_get('clio_search_geocode_url', ''),
    '#element_validate' => array('clio_validate_api'),
  );
  return system_settings_form($form);
}


/*
 * Show a filter form with years, countries and indicators.
 */
function clio_search_select_form($form, &$form_state, $type = 'modern') {
  $type = ($type == 'historical') ? 'historical' : 'modern';
  $title = "Select ($type)";
  drupal_set_title($title);

  $searchbox = <<<EOB
selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder=''>",
afterInit: function(ms){
  var that = this,
      \$selectableSearch = that.\$selectableUl.prev(),
      selectableSearchString = '#'+that.\$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)';

  that.qs1 = \$selectableSearch.quicksearch(selectableSearchString)
  .on('keydown', function(e){
    if (e.which === 40){
      that.\$selectableUl.focus();
      return false;
    }
  });
},
afterSelect: function(){
  this.qs1.cache();
},
afterDeselect: function(){
  this.qs1.cache();
}
EOB;

  $block_submit = <<<EOB
jQuery('#clio-search-select-form').on('keyup keypress', function(e) {
  var code = e.keyCode || e.which;
  if (code == 13) { 
    e.preventDefault();
    return false;
  }
});
EOB;

  $form['#action'] = url('datasets/searchresults');
  // Only submit form by clicking submit, to prevent accidental queries.
  $form['#attached']['js'] = array(
    array(
     'data' => $block_submit,
     'type' => 'inline',
     'scope' => 'footer',
    ),
  );

  if ($type == 'modern') {
   $help = t('Datasets converted to modern boundaries.');
  }
  else {
   $help = t('Datasets according to historical boundaries. Start typing and suggested country names will appear.');
  }
  $form['help'] = array(
    '#prefix' => '<div class="select-help">',
    '#markup' => $help,
    '#suffix' => '</div>',
  );

  // Attach libraries to the first element, so they get loaded first.
  $form['help']['#attached']['libraries_load'][] = array('multiselect.js');
  $form['help']['#attached']['libraries_load'][] = array('quicksearch');

  $form['year'] = array (
    '#prefix' => '<div class="time-period">',
    '#tree' => TRUE,
    '#title' => t('Time period'),
    '#suffix' => '</div>',
  );
  $form['year']['min'] = array (
    '#type' => 'textfield',
    '#title' => t('from'),
    '#size' => 4,
    '#default_value' => CLIO_MIN_YEAR,
  );
  $form['year']['max'] = array (
    '#type' => 'textfield',
    '#title' => t('to'),
    '#size' => 4,
    '#default_value' => CLIO_MAX_YEAR,
  );

  if (!($options = clio_search_taxonomy_options('indicators'))) {
    drupal_set_message(t('No indicators available.'), 'error');
  }
  $form['indicator'] = array(
    '#type' => 'select',
    '#title' => t('Indicators'),
    '#options' => $options,
    '#multiple' => TRUE,
    '#size' => 14,
    '#attached' => array(
      'js' => array(
        array(
         'data' => "jQuery('#edit-indicator').multiSelect({{$searchbox}})",
         'type' => 'inline',
         'scope' => 'footer',
        ),
      ),
    ),
  );
  
  if ($type == 'modern') {
    if ($options = clio_search_taxonomy_options('countries')) {
      $selectall = ", selectableFooter: \"<a href='#' id='select-all-countries'>select all</a>\"";
      $selectall .= ", selectionFooter: \"<a href='#' id='deselect-all-countries'>deselect all</a>\"";
    }
    else {
      drupal_set_message(t('No countries available.'), 'error');
      $selectall = '';
    }
    $form['country'] = array(
      '#type' => 'select',
      '#title' => t('Countries'),
      '#options' => $options,
      '#multiple' => TRUE,
      '#size' => 14,
      '#attached' => array(
        'js' => array(
          array(
           'data' => "jQuery('#edit-country').multiSelect({{$searchbox}{$selectall}})",
           'type' => 'inline',
           'scope' => 'footer',
          ),
          array(
           'data' => "jQuery('#select-all-countries').click(function(){jQuery('#edit-country').multiSelect('select_all'); return false;})",
           'type' => 'inline',
           'scope' => 'footer',
          ),
          array(
           'data' => "jQuery('#deselect-all-countries').click(function(){jQuery('#edit-country').multiSelect('deselect_all'); return false;})",
           'type' => 'inline',
           'scope' => 'footer',
          ),
        ),
      ),
    );
    $form['type'] = array (
      '#type' => 'hidden',
      '#value' => 'modern',
    );
  }
  else {
    $form['help']['#attached']['libraries_load'][] = array('jquery.typeahead');
    $form['country'] = array(
      '#type' => 'select',
      '#title' => t('Countries'),
      '#options' => array(),
      '#multiple' => TRUE,
      '#size' => 14,
      '#prefix' => '<div class="typeahead-container"><div class="typeahead-field">',
      '#suffix' => '</div></div>', 
      '#attached' => array(      
        'js' => array(drupal_get_path('module', 'clio_search') . '/js/clio-search-historical.js'),
        'css' => array(drupal_get_path('module', 'clio_search') . '/css/clio-search.css'),
      ),
    );
    $form['country']['#attached']['js'][] = array(
      'type' => 'setting',
      'data' => array('clioSearch' => array(
        'geocodeapi' => variable_get('clio_search_geocode_url', ''),
      )),
    );                      
    $form['type'] = array (
      '#type' => 'hidden',
      '#value' => 'historical',
    );
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('OK'),
  );

  return $form;  
}


/*
 * Show table of available indicators/datasets based on query
 * with button to download all result files in zip.
 */
function clio_search_results() {
  $params = clio_search_get_params();
  if (!($path = variable_get('clio_search_search_url', ''))) {
    drupal_set_message("No search API configured.", 'error');
  }
  else {
    $query = array();
    foreach ($params as $key => $value) {
      if (!empty($value)) {
        $query[$key] = $value;
      }
    }
    $querylink = l("query", $path, array('query' => $query));
    // TODO request search api and receive results
    // Obviously this should be a POST
  }
  
  $indicators = $params['indicator'];
  
  $datasets = array();
  foreach ($indicators as $indicatortid) {
    $datasets[$indicatortid] = array(
      'datasetid' => 'hdl:10622/F16UDU',
//      'datasetid' => 'hdl:10622/0HOJBV',
      'title' => 'Example dataset title',
      'description' => 'A short description of the dataset',
    );

/*
    $result = clio_search_db_query($indicatortid, $params['year'], $params['country'], 1);
    if ($result->rowCount()) {
      $indicator = taxonomy_term_load($indicatortid);
      $topics = taxonomy_get_parents($indicatortid);
      $topic  = array_shift($topics);
      $datasets[$indicatortid] = array(
        'dataset' => $datasetnid,
        'resource' => $resourcenid,
        'indicator' => $indicator->name,
        'topic' => $topic->name,
      );
    }
*/
  }

  if (count($datasets)) {
    // The table with results.
//    $select = '<input type="checkbox" value="Download" name="id">';
    $select = '';
    $header = array($select, t('Dataset'), t('Description'), '');
    $rows = array();
    unset($params['indicator']); // TODO: always set?
    foreach ($datasets as $tid => $info) {
      $downloadform = drupal_get_form('clio_search_download_form', $params, $info['datasetid']);
      $buttons = drupal_render($downloadform);
      $rows[] = array($select, $info['title'],  $info['description'], $buttons);
    }
    $content = '<div class="searchresults">';
    $content .= theme('table', array('header' => $header, 'rows' => $rows, 'sticky' => FALSE));
    $content .= '</div>';
    
    // The download button.
//    $downloadform = drupal_get_form('clio_search_download_multiple_form', $params);
//    $content .= drupal_render($downloadform);
  }
  else {
    $content = "No results";
  }
  drupal_set_title("Search results");
  // TODO display selection?
  $content = '<div>' . $querylink . '</div>' . $content;
  return $content;
}


/*
 *  Create download button.
 *
 * @param $id
 *   The dataset id.
 */
function clio_search_download_form($form, &$form_state, $params, $id) {
  $form['#action'] = url('datasets/download');
  $form['datasetid'] = array(
    '#type' => 'hidden',
    '#value' => $id,
  );
  foreach ($params as $field => $values) {
    $form[$field] = array(
      '#type' => 'value',
      '#tree' => TRUE,
    );
    foreach ($values as $key => $value) {
      $form[$field][$key] = array(
        '#type' => 'hidden', // Cannot be value as we need it in the params.
        '#value' => $value,
      );
    }
  }
  $form['download'] = array(
    '#type' => 'submit',
    '#value' => t('Download'),
    '#prefix' => '<span class="search-submit-download">',
    '#suffix' => '</span>',
  );
  if (module_exists('clio_analyze') && variable_get('clio_analyze_default', '')) {
    $form['analyze'] = array(
      '#type' => 'submit',
      '#value' => t('Analyze'),
      '#prefix' => '<span class="search-submit-analyze">',
      '#suffix' => '</span>',
    );
  }
  return $form;
}


/*
 *  Create download button.
 *
 * @param $params
 *   The search parameters (year, topic, indicator, country).
 */
function clio_search_download_multiple_form($form, &$form_state, $params) {
  $form['#action'] = url('datasets/download/multiple');
  foreach ($params as $field => $values) {
    $form[$field] = array(
      '#type' => 'value',
      '#tree' => TRUE,
    );
    foreach ($values as $key => $value) {
      $form[$field][$key] = array(
        '#type' => 'hidden', // Cannot be value as we need it in the params.
        '#value' => $value,
      );
    }
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Download selected'),
    '#prefix' => '<div class="search-submit-multiple">',
    '#suffix' => '</div>',
  );
  return $form;
}


/*
 * Transfer the created zip file to the client.
 */
function clio_search_download() {
  $params = clio_search_get_params(TRUE);
  // TODO validate input
  $datasetid = $params['datasetid'];
// drupal_set_message(print_r($params,TRUE));
  if ($params['op'] == 'Download') {
    $download_url = variable_get('clio_search_download_url', '');
    if ($download_url) {
      drupal_goto($download_url, array('query' => array('persistentId' => $datasetid)));
    }
  }
  else if (($params['op'] == 'Analyze') && (module_exists('clio_analyze'))) {
    drupal_goto('analyze/' . rawurlencode($datasetid));
  }
  else {
    drupal_set_message('An error occurred while creating the download file.', 'error');
    drupal_goto('/datasets');
  }
}


function clio_search_download_form_submit() { 
  $params = clio_search_get_params();  
  $indicators = $params['indicator'];
}


/*
 * Get type, years, countries and indicators from the querystring.
 * Make sure type is correct and all other values are numeric.
 *
 * TODO validate op and datasetid.
 *
 * @return
 *   An array of arrays containing type, year, country and indicator.
 */
function clio_search_get_params($include = FALSE) {
  $query = drupal_get_query_parameters();
  if (empty($query)) {
    $query = drupal_get_query_parameters($_POST);
  }
  $type = isset($query['type']) && in_array($query['type'], array('modern', 'historical')) ? array($query['type']) : array();
  $years = isset($query['year']) ? array_filter($query['year'], 'is_numeric') : array();
  $countries = isset($query['country']) ? array_filter($query['country'], 'is_numeric') : array();
  if (isset($query['indicator'])) {
    $indicators = array_filter($query['indicator'], 'is_numeric');
  }
  else {
    if (isset($query['topic']) && is_numeric($query['topic'])) {
      $indicators = array();
      $children = taxonomy_get_children($query['topic']);
      foreach ($children as $child) {
        $indicators[] = $child->tid;
      }
    }
    else {
      $indicators = array();
    }
  }
  if ($include) {
    $op = isset($query['op']) && in_array($query['op'], array('Download', 'Analyze')) ? $query['op'] : '';
    $datasetid = isset($query['datasetid']) ? $query['datasetid'] : '';
    return array('type' => $type, 'year' => $years, 'country' => $countries, 'indicator' => $indicators, 'op' => $op, 'datasetid' => $datasetid);
  }
  else {
    return array('type' => $type, 'year' => $years, 'country' => $countries, 'indicator' => $indicators);
  }
}


/*
 * Get only the leaves of a term tree.
 *
 * @param $machine_name
 *   A vocabulary machine name.
 * @param $parent
 *   The parent tid to start from.
 *
 * @return
 *   An array of term names keyed by tid, sorted by name.
 */
function clio_search_taxonomy_get_leaves($machine_name, $parent = 0) {
  $v = taxonomy_vocabulary_machine_name_load($machine_name);
  $terms = taxonomy_get_tree($v->vid, $parent);
  foreach ($terms as $term) {
    if (!(taxonomy_get_children($term->tid, $v->vid))) {
      $options[$term->tid] = $term->name;
    }
  }
  asort($options);
  return $options;
}


function clio_search_taxonomy_options($machine_name) {
  $options = array();
  $vocabulary = taxonomy_vocabulary_machine_name_load($machine_name);
  $tree = taxonomy_get_tree($vocabulary->vid);
  foreach ($tree as $item) {
    $options[$item->tid] = str_repeat('-', $item->depth) . ' ' . $item->name;
  }
  return $options;
}


/**
 * Get vocabulary in a hierarchical array, so we can show first level as (non-selectable) optgroups.
 */
function clio_search_get_selectlist($name) {
  $options = array();
  $vocabulary = taxonomy_vocabulary_machine_name_load($name);
  $tree = _taxonomy_get_nested_tree($vocabulary->vid);
  foreach ($tree as $item) {
    if (isset($item->children)) {
      $options_children = array();
      foreach ($item->children as $child_item) {
        $options_children[$child_item->tid] = $child_item->name;
      }
      if ($options_children) {
        // Show topic as optgroup.
        $options[$item->name] = $options_children;
      }
    }
    else {
      $options[$item->tid] = $item->name;
    }
  }
  return $options;
}


/**
 * Get a vocabulary as a hierarchical array.
 * https://api.drupal.org/comment/50023#comment-50023
 */
function _taxonomy_get_nested_tree($vid_or_terms, $max_depth = NULL, $parent = 0, $parents_index = array(), $depth = 0) {
  if (!is_array($vid_or_terms)) {
    $vid_or_terms = taxonomy_get_tree($vid_or_terms);
  }
  foreach ($vid_or_terms as $term) {
    foreach ($term->parents as $term_parent) {
      if ($term_parent == $parent) {
        $return[$term->tid] = $term;
      }
      else {
        $parents_index[$term_parent][$term->tid] = $term;
      }
    }
  }
  foreach ($return as &$term) {
    if (isset($parents_index[$term->tid]) && (is_null($max_depth) || $depth < $max_depth)) {
      $term->children = _taxonomy_get_nested_tree($parents_index[$term->tid], $max_depth, $term->tid, $parents_index, $depth + 1);
    }
  }
  return $return;
}


